# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import hub_pb2 as hub__pb2
from . import tag_pb2 as tag__pb2


class HubStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartAdvertisementScanning = channel.unary_unary(
                '/gateway.Hub/StartAdvertisementScanning',
                request_serializer=hub__pb2.HubCommand.SerializeToString,
                response_deserializer=hub__pb2.HubResponse.FromString,
                )
        self.GetTags = channel.unary_stream(
                '/gateway.Hub/GetTags',
                request_serializer=hub__pb2.GetTagRequest.SerializeToString,
                response_deserializer=tag__pb2.Tag.FromString,
                )


class HubServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartAdvertisementScanning(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartAdvertisementScanning': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAdvertisementScanning,
                    request_deserializer=hub__pb2.HubCommand.FromString,
                    response_serializer=hub__pb2.HubResponse.SerializeToString,
            ),
            'GetTags': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTags,
                    request_deserializer=hub__pb2.GetTagRequest.FromString,
                    response_serializer=tag__pb2.Tag.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gateway.Hub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Hub(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartAdvertisementScanning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gateway.Hub/StartAdvertisementScanning',
            hub__pb2.HubCommand.SerializeToString,
            hub__pb2.HubResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/gateway.Hub/GetTags',
            hub__pb2.GetTagRequest.SerializeToString,
            tag__pb2.Tag.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
